# Generated by Django 6.0.5 on 2026-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_notes_application_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Done', 'Interview Done'), ('Evaluated', 'Evaluated'), ('Offer Sent', 'Offer Sent'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
    ]
