# Generated by Django 6.0.5 on 2026-05-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_candidate_email_remove_candidate_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='candidate_cvs/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
